// INCLUDE FILE generated by "Pelles C for Windows, version 1.00".

//#pragma warning( disable: 4996 )

#ifndef __MAIN_H
#define __MAIN_H


#define WIN32_LEAN_AND_MEAN  /* speed up compilations */
#if !defined( _WIN32_IE)
#define _WIN32_IE 0x0401
#endif

#include <windows.h>
#include <windowsx.h>
#include <shellapi.h>
#include <commctrl.h>
#include <commdlg.h>
#include <tchar.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include "resource.h"

#define NOTIFY_ICON_MESSAGE		(WM_USER + 100)
#define NOTIFY_LOGGER_STATUS    (WM_USER + 101)
#define APPLICATION_NAME		"BRWATCH"

char *GetApplicationPath( void );
HWND MainWindowGetHandle( void );
int ResourcesGetImageIndex( WORD resource );
int ResourcesGetPviObjectImage( PVIOBJECT *object );

HWND g_hwndMainWindow;
HINSTANCE g_hInstance;
PVIOBJECT *g_draggedPVIObject;
PVIOBJECT *g_selectedPVIObject;
char g_PVIVersionString[50];

#endif
