// Used by main.rc
//
#define DLG_AXCONFIG                    9
#define IDR_DEFAULT_INI1                115
#define DLG_SETTINGS                    117
#define IDR_MNU_PLOT                    121
#define DLG_ETH_ADAPTERS                122
#define DLG_ABOUT                       1001
#define IDC_STATIC_PVIVERSION           1002
#define DLG_WRITE_PVAR                  1004
#define DLG_LOGGER_CONFIG               1005
#define IDS_ZLIB2                       1006
#define IDC_STATIC_TASK                 1007
#define IDC_STATIC_CPU                  1008
//#define IDC_CHECK1                      1009
#define IDS_ZLIB1                       1010
#define IDC_STATIC_VARTYPE              1011
#define IDC_EDIT_YEAR                   1013
#define IDC_EDIT_MONTH                  1014
#define IDC_EDIT_DAY                    1015
#define IDC_EDIT_HOUR                   1016
#define IDC_EDIT_MINUTE                 1017
#define IDC_EDIT_MILLISECONDS           1018
#define IDC_EDIT1                       1022
#define IDC_STATIC_MODULENAME           1023
#define IDC_LIST                        1026
#define IDC_CHECK_CHANGED               1027
#define IDR_MNU_MAIN                    2001
#define IDR_LVPVIOBJECTS                4001
#define IDR_LVTASKLIST                  4003
#define IDM_ABOUT                       6001
#define IDM_STATUSPVIOBJEKTE            6002
#define IDM_MNU_REFRESH                 6003
#define IDM_SAVE_WATCH_FILE             6004
#define IDM_LOAD_WATCH_FILE             6005
#define IDM_CHANGE_VIEW_DECIMAL         6101
#define IDM_CHANGE_VIEW_HEX             6102
#define IDM_CHANGE_VIEW_BINARY          6103
#define IDM_CHANGE_VIEW_CHAR            6104
#define IDM_CHANGE_VIEW_OEMCHAR         6105
#define IDM_SEND_ICMP                   6106
#define IDM_DELETE_OBJECT_FROM_LIST		6107
#define IDM_LOGGER_CONFIG               6201
#define IDM_LOGGER_START                6202
#define IDR_ICO_MAIN                    8001
#define IDR_ICO_PVI                     8002
#define IDR_ICO_TASK                    8003
#define IDR_ICO_STRUCT                  8004
#define IDR_ICO_CPU                     8005
#define IDR_ICO_VARIABLE                8006
#define IDR_ICO_GLOBAL                  8007
#define IDR_ICO_ARRAY                   8008
#define IDR_ICO_VARIABLE_U32            8009
#define IDR_ICO_VARIABLE_I32            8010
#define IDR_ICO_VARIABLE_U16            8011
#define IDR_ICO_VARIABLE_I16            8012
#define IDR_ICO_VARIABLE_U8             8013
#define IDR_ICO_VARIABLE_I8             8014
#define IDR_ICO_VARIABLE_BOOL           8015
#define IDR_ICO_VARIABLE_STRING         8016
#define IDR_ICO_VARIABLE_REAL           8017
#define IDR_ICO_VARIABLE_DATE_AND_TIME  8018
#define IDR_ICO_VARIABLE_TIME           8019
#define IDR_ICO_DEVICE                  8020
#define IDR_ICO_PLOT                    8021
#define IDR_STATIC_VERSION              8200
#define IDR_STATIC_NAME                 8201
#define IDR_EDIT_VALUE                  8202
#define IDR_EDIT_FILENAME               8203
#define IDR_BUTTON_FILESELECT           8204
#define IDR_EDIT_MAXSIZE                8205
#define IDR_EDIT_TIMESTAMP_CPU          8206
#define IDR_EDIT_CYCLETIME              8207
#define IDR_EDIT_OBJECT_COUNT           8208
#define IDC_CHECK_ZIP                   8209
#define IDM_LOGGER_UNZIPLOGGERFILE      40002
#define IDM_OPTIONS_SETTINGS            40004
#define IDM_VIEW_SELECT_FONT            40006
#define IDM_VIEW_SETDEFAULTFONT         40008
#define ID_LOGGER_OPENLOGGERFILE        40012
#define ID_TRACE_TRACE1                 40013
#define ID_TRACE_TRACE2                 40014
#define ID_TRACE_TRACE3                 40015
#define ID_TRACE_TRACE4                 40016
#define ID_TRACE_TRACE5                 40017
#define ID_TRACE_TRACE6                 40018
#define ID_TRACE_TRACE7                 40019
#define ID_TRACE_TRACE8                 40020
#define ID_TRACE_TRACE9                 40021
#define ID_TRACE_TRACE10                40022
#define ID_TRACE_TRACE11                40023
#define ID_TRACE_TRACE12                40024
#define Trace                           40025
#define ID_Menu                         40026
#define ID_PLOT_TRACE                   40028
#define IDR_BUTTON_DEVICE1              40029
#define IDR_BUTTON_DEVICE2              40030
#define ID_APPLY                        40031
#define IDC_STATIC                      -1

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        128
#define _APS_NEXT_COMMAND_VALUE         40029
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
